service: matching-service

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1
  stage: prod
  lambdaHashingVersion: 20201221
  logs:
    httpApi: false # disables CloudWatch access logs for HTTP APIs

  environment:
    MATCHING_SERVICE_PORT: ${env:MATCHING_SERVICE_PORT}
    ENV: ${env:ENV}
    KAFKA_BROKERS: ${env:KAFKA_BROKERS}
    KAFKA_USERNAME: ${env:KAFKA_USERNAME}
    KAFKA_PASSWORD: ${env:KAFKA_PASSWORD}
    REDIS_URL: ${env:REDIS_URL}

functions:
  matching:
    handler: lambda.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY

package:
  patterns:
    - "!node_modules/aws-sdk/**"
    - "**"
