service: notifcation-service

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1
  stage: prod
  lambdaHashingVersion: 20201221
  logs:
    httpApi: false # disables CloudWatch access logs for HTTP APIs

  environment:
    NOTIFICATION_SERVICE_PORT: ${env:NOTIFICATION_SERVICE_PORT}
    ENV: ${env:ENV}
    REDIS_URL: ${env:REDIS_URL}

functions:
  notifcation:
    handler: lambda.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY

package:
  patterns:
    - "!node_modules/aws-sdk/**"
    - "**"
