service: notifcation-service

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1
  stage: prod
  lambdaHashingVersion: 20201221
  logs:
    httpApi: false # disables CloudWatch access logs for HTTP APIs
  httpApi:
    cors:
      allowedOrigins:
        - https://d2a6nuxq78ul43.cloudfront.net
        - http://localhost:5173
        - http://localhost:5174
        - http://127.0.0.1:5173
      allowedMethods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      allowedHeaders:
        - Content-Type
        - Authorization
        - X-Requested-With
        - Accept
        - Origin
      allowCredentials: true

  environment:
    NOTIFICATION_SERVICE_PORT: ${env:NOTIFICATION_SERVICE_PORT}
    ENV: ${env:ENV}
    REDIS_URL: ${env:REDIS_URL}

functions:
  notifcation:
    handler: lambda.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY

package:
  patterns:
    - "!node_modules/aws-sdk/**"
    - "**"
