service: question-service

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1
  stage: prod
  lambdaHashingVersion: 20201221
  logs:
    httpApi: false # disables CloudWatch access logs for HTTP APIs
  httpApi:
  cors:
    allowedOrigins:
      - https://d2a6nuxq78ul43.cloudfront.net
      - http://localhost:5173
      - http://localhost:5174
      - http://127.0.0.1:5173
    allowedMethods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      - OPTIONS
    allowedHeaders:
      - Content-Type
      - Authorization
      - X-Requested-With
      - Accept
      - Origin
    allowCredentials: true

  environment:
    PORT: ${env:QUESTION_SERVICE_PORT}
    DB_LOCAL_URI: ${env:DB_LOCAL_URI}
    DB_CLOUD_URI: ${env:DB_CLOUD_URI}
    ENV: ${env:ENV}
    JWT_SECRET: ${env:JWT_SECRET}
    KAFKA_BROKERS: ${env:KAFKA_BROKERS}
    KAFKA_USERNAME: ${env:KAFKA_USERNAME}
    KAFKA_PASSWORD: ${env:KAFKA_PASSWORD}
    CLOUDINARY_CLOUD_NAME: ${env:CLOUDINARY_CLOUD_NAME}
    CLOUDINARY_API_KEY: ${env:CLOUDINARY_API_KEY}
    CLOUDINARY_API_SECRET: ${env:CLOUDINARY_API_SECRET}
    API_GATEWAY_URL: ${env:API_GATEWAY_URL}

functions:
  quesiton:
    handler: lambda.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY

package:
  patterns:
    - "!node_modules/aws-sdk/**"
    - "**"
