service: user-service

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1
  stage: prod
  lambdaHashingVersion: 20201221
  logs:
    httpApi: false # disables CloudWatch access logs for HTTP APIs

  environment:
    USER_SERVICE_PORT: ${env:USER_SERVICE_PORT}
    DB_LOCAL_URI: ${env:DB_LOCAL_URI}
    DB_CLOUD_URI: ${env:DB_CLOUD_URI}
    ENV: ${env:ENV}
    JWT_SECRET: ${env:JWT_SECRET}
    GOOGLE_CLIENT_ID: ${env:GOOGLE_CLIENT_ID}
    GOOGLE_CLIENT_SECRET: ${env:GOOGLE_CLIENT_SECRET}
    GOOGLE_CALLBACK_URL: ${env:GOOGLE_CALLBACK_URL}
    GITHUB_CLIENT_ID: ${env:US_GITHUB_CLIENT_ID}
    GITHUB_CLIENT_SECRET: ${env:US_GITHUB_CLIENT_SECRET}
    GITHUB_CALLBACK_URL: ${env:US_GITHUB_CALLBACK_URL}
    CLOUDINARY_URL: ${env:CLOUDINARY_URL}
    SENDGRID_API_KEY: ${env:SENDGRID_API_KEY}
    EMAIL_FROM: ${env:EMAIL_FROM}
    FRONTEND_ORIGIN: ${env:FRONTEND_ORIGIN}
    EMAIL_VERIFICATION_URL: ${env:EMAIL_VERIFICATION_URL}
    EMAIL_VERIFICATION_TTL_HOURS: ${env:EMAIL_VERIFICATION_TTL_HOURS}

functions:
  user:
    handler: lambda.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY

package:
  patterns:
    - "!node_modules/aws-sdk/**"
    - "**"
